# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy application code
COPY app.py /app/
COPY templates /app/templates

# Install dependencies
RUN pip install flask

# Expose port 5000
EXPOSE 5000

# Start the Flask application
CMD ["python", "app.py"]
